apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch-dashboards.serviceName" . }}
  namespace: {{ include "opensearch-dashboards.namespace" . }}
  labels:
    {{- include "opensearch-dashboards.serviceLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "opensearch-dashboards.serviceSelectorLabels" . | nindent 4 }}
